const colors = {
  HTML: "orange",
  CSS: "blue",
  NodeJS: "green",
  React: "blue",
  ExpressJS: "purple",
  Knex: "pink",
  SQLite: "indigo",
  Figma: "red",
  Photoshop: "blue",
  Compreensão: "yellow",
  Comunicação: "pink",
  Design: "yellow",
  Prototipagem: "teal",
  Testes: "violet",
  Acessibilidade: "green",
  MobileFirst: "purple",
  Lógica: "yellow",
  API: "blue",
  SQL: "orange",
  PostgreSQL: "indigo",
  Joi: "teal",
  JavaScript: "yellow",
  "Desenvolvimento Web": "purple",
  "Desenvolvimento Mobile": "yellow",
  "Engenharia de Software": "teal",
  "Segurança da Informação": "indigo",
  "Banco de Dados": "pink",
  "Estrutura de Dados": "purple",
  "Programação Orientada a Objetos": "teal",
  Algoritmos: "red", // Adicionado "red" para Algoritmos
};

export default colors;
