const cursos = [
    {
        id: 4,
        local: 'Unifatecie, Natal-RN',
        data: 'Junho de 2023 - Junho de 2025',
        titleCurse: 'Análise e Desenvolvimento de Sistemas',
        softSkills: [
            'Orientação para Resultados',
            'Mentalidade de Aprendizado',
            'Pensamento Estratégico',
            'Visão Sistêmica',
            'Compreensão Tecnológica',
        ],
        hardSkills: [
            'Algoritmos',
            'Estrutura de Dados',
            'Programação Orientada a Objetos',
            'Banco de Dados',
            'Desenvolvimento Web',
            'Desenvolvimento Mobile',
            'Engenharia de Software',
            'Segurança da Informação',
        ],
        image: 'https://i.ytimg.com/vi/xeKs2wZgL40/maxresdefault.jpg',
    },
    {
        id: 3,
        local: 'Cubos Academy, Salvador-BA',
        data: 'Julho de 2023 - Novembro de 2023',
        titleCurse: 'Desenvolvimento Backend',
        softSkills: [
            'Liderança',
            'Adaptabilidade',
            'Empatia',
            'Resiliência',
            'Pensamento Crítico',
        ],

        hardSkills: [
            'JavaScript',
            'NodeJS',
            'ExpressJS',
            'API',
            'SQL',
            'PostgreSQL',
            'Knex',
            'Joi',
            'Lógica',
        ],
        image: 'https://raw.githubusercontent.com/tonelopes-dev/portfolio-v2/main/src/assets/capa-cubos-academy.png',
    },
    {
        id: 1,
        local: 'Rocketseat Digital House, Rio do Sul-SC',
        data: 'Novembro de 2022 - Junho de 2023',
        titleCurse: 'Desenvolvimento Full Stack',
        softSkills: [
            'Trabalho em Equipe',
            'Comunicação',
            'Resolução de Problemas',
            'Gestão do Tempo',
            'Organização',
        ],

        hardSkills: [
            'HTML',
            'CSS',
            'NodeJS',
            'React',
            'ExpressJS',
            'Knex',
            'SQLite',
        ],
        image: 'https://raw.githubusercontent.com/tonelopes-dev/portfolio-v2/main/src/assets/capa-explorer.jpeg',
    },
    {
        id: 2,
        local: 'Universidade Potiguar , Natal-RN',
        data: 'Junho de 2016 - Junho de 2018',
        titleCurse: 'Tecnólogo em Design Gráfico',
        softSkills: [
            'Criatividade e inovação no design',
            'Colaboração em equipes multidisciplinares',
            'Comunicação visual eficaz',
            'Capacidade de adaptação a diferentes estilos e necessidades',
            'Gestão de projetos de design',
        ],
        hardSkills: [
            'Figma',
            'Photoshop',
            'Design',
            'Prototipagem',
            'Compreensão',
            'MobileFirst',
            'Testes',
            'Acessibilidade',
            'Comunicação',
        ],

        image: 'https://raw.githubusercontent.com/tonelopes-dev/portfolio-v2/main/src/assets/capa-unp.jpg',
    },
]
export default cursos
